### ISSUE TITLE
Auto complete location

### ISSUE THREAD

**Issue by RowanPage05** [jacoduplessis/should-i-drive#5]
When typing in to and from search bars there needs to be a drop down of options which can be selected from.

This will improve user experience

**Comment by RowanPage05** [comment]
Also stack on mobile

**Comment by jacoduplessis** [comment]
I think this is the simplest solution for now. Showing the result in the search box, then the person should hopefully realise why an unexpected result may have occurred.

https://user-images.githubusercontent.com/11544263/182530893-acde6151-cd76-4613-bef1-2e794d3f2285.mp4
